// Define an array of paragraphs
const paragraphs = [
    'Some such experience as this awaits us when we begin the study of literature, which has always two aspects, one of simple enjoyment and appreciation, the other of analysis and exact description. Let a little song appeal to the ear, or a noble book to the heart, and for the moment, at least, we discover a new world, a world so different from our own that it seems a place of dreams and magic. To enter and enjoy this new world, to love good books for their own sake, is the chief thing; to analyze and explain them is a less joyous but still an important matter. Behind every book is a man; behind the man is the race; and behind the race are the natural and social environments whose influence is unconsciously reflected. These also we must know, if the book is to speak its whole message. In a word, we have now reached a point where we wish to understand as well as to enjoy literature; and the first step, since exact definition is impossible, is to determine some of its essential qualities.',

    "The Revolution of 1688, which banished the last of the Stuart kings and called William of Orange to the throne, marks the end of the long struggle for political freedom in England. Thereafter the Englishman spent his tremendous energy, which his forbears had largely spent in fighting for freedom, in endless political discussions and in efforts to improve his government. In order to bring about reforms, votes were now necessary; and to get votes the people of England must be approached with ideas, facts, arguments, information. So the newspaper was born, and literature in its widest sense, including the book, the newspaper, and the magazine, became the chief instrument of a nation's progress.",

    "The place was large, well lighted, and comfortably warmed; good pictures hung on the walls, and racks of books filled every available nook. At the upper end of the room, near the master's desk, stood an open piano; and at the lower, a table bearing plates, cups, and wholesome refreshments which would be distributed among the boys when study-hour was over. Throughout the room great cheerfulness and comfort reigned, and the apple-cheeked boys at the desks showed that they were generously cared for under this kindly roof. They were mostly little fellows, ranging in age from eight to twelve years, and a merrier company one would journey far to find.",

    "Mind can be observed and known. But each one can know directly only his own mind, and not another's. You and I may look into each other's face and there guess the meaning that lies back of the smile or frown or flash of the eye, and so read something of the mind's activity. But neither directly meets the other's mind. I may learn to recognize your features, know your voice, respond to the clasp of your hand; but the mind, the consciousness, which does your thinking and feels your joys and sorrows, I can never know completely. Indeed I can never know your mind at all except through your bodily acts and expressions. Nor is there any way in which you can reveal your mind, your spiritual self, to me except through these means.",

    "One should always keep in mind that psychology is essentially a laboratory science, and not a text-book subject. The laboratory material is to be found in ourselves and in those about us. While the text should be thoroughly mastered, its statements should always be verified by reference to one's own experience, and observation of others. Especially should prospective teachers constantly correlate the lessons of the book with the observation of children at work in the school. The problems suggested for observation and introspection will, if mastered, do much to render practical and helpful the truths of psychology.",

    'Education was long looked upon as affecting the mind only; the body was either left out of account or neglected. Later science has shown, however, that the mind cannot be trained except as the nervous system is trained and developed. For not sensation and the simpler mental processes alone, but memory, imagination, judgment, reasoning and every other act of the mind are dependent on the nervous system finally for their efficiency. The little child gets its first mental experiences in connection with certain movements or acts set up reflexly by the pre-organized nervous system. From this time on movement and idea are so inextricably bound together that they cannot be separated. The mind and the brain are so vitally related that it is impossible to educate one without performing a like office for the other; and it is likewise impossible to neglect the one without causing the other to suffer in its development.',

    "This book, which presents the whole splendid history of English literature from Anglo-Saxon times to the close of the Victorian Era, has three specific aims. The first is to create or to encourage in every student the desire to read the best books, and to know literature itself rather than what has been written about literature. The second is to interpret literature both personally and historically, that is, to show how a great book generally reflects not only the author's life and thought but also the spirit of the age and the ideals of the nation's history. The third aim is to show, by a study of each successive period, how our literature has steadily developed from its first simple songs and stories to its present complexity in prose and poetry.",

    "To those who may use this book in their homes or in their class rooms, the writer ventures to offer one or two friendly suggestions out of his own experience as a teacher of young people. First, the amount of space here given to different periods and authors is not an index of the relative amount of time to be spent upon the different subjects. Thus, to tell the story of Spenser's life and ideals requires as much space as to tell the story of Tennyson; but the average class will spend its time more pleasantly and profitably with the latter poet than with the former. Second, many authors who are and ought to be included in this history need not be studied in the class room. A text-book is not a catechism but a storehouse, in which one finds what he wants, and some good things beside.",

    "Indeed, many mature persons (including the writer of this history) are often unable to explain at first the charm or the style of an author who pleases them; and the more profound the impression made by a book, the more difficult it is to give expression to our thought and feeling. To read and enjoy good books is with us, as with Chaucer, the main thing; to analyze the author's style or explain our own enjoyment seems of secondary and small importance. However that may be, we state frankly our own conviction that the detailed study and analysis of a few standard works, which is the only literary pabulum given to many young people in our schools, bears the same relation to true literature that theology bears to religion, or psychology to friendship. One is a more or less unwelcome mental discipline; the other is the joy of life.",

    'In the same pleasing, surprising way, all artistic work must be a kind of revelation. Thus architecture is probably the oldest of the arts; yet we still have many builders but few architects, that is, men whose work in wood or stone suggests some hidden truth and beauty to the human senses. So in literature, which is the art that expresses life in words that appeal to our own sense of the beautiful, we have many writers but few artists. In the broadest sense, perhaps, literature means simply the written records of the race, including all its history and sciences, as well as its poems and novels; in the narrower sense literature is the artistic record of life, and most of our writing is excluded from it, just as the mass of our buildings, mere shelters from storm and from cold, are excluded from architecture. A history or a work of science may be and sometimes is literature, but only as we forget the subject-matter and the presentation of facts in the simple beauty of its expression.',

    'In a word, our whole civilization, our freedom, our progress, our homes, our religion, rest solidly upon ideals for their foundation. Nothing but an ideal ever endures upon earth. It is therefore impossible to overestimate the practical importance of literature, which preserves these ideals from fathers to sons, while men, cities, governments, civilizations, vanish from the face of the earth. It is only when we remember this that we appreciate the action of the devout Mussulman, who picks up and carefully preserves every scrap of paper on which words are written, because the scrap may perchance contain the name of Allah, and the ideal is too enormously important to be neglected or lost.',

    'The Venerable Bede, as he is generally called, our first great scholar and "the father of our English learning," wrote almost exclusively in Latin, his last work, the translation of the Gospel of John into Anglo-Saxon, having been unfortunately lost. Much to our regret, therefore, his books and the story of his gentle, heroic life must be excluded from this history of our literature. His works, over forty in number, covered the whole field of human knowledge in his day, and were so admirably written that they were widely copied as text-books, or rather manuscripts, in nearly all the monastery schools of Europe.',

    "Side by side with this historical exactness are marvelous stories of saints and missionaries. It was an age of credulity, and miracles were in men's minds continually. The men of whom he wrote lived lives more wonderful than any romance, and their courage and gentleness made a tremendous impression on the rough, warlike people to whom they came with open hands and hearts. It is the natural way of all primitive peoples to magnify the works of their heroes, and so deeds of heroism and kindness, which were part of the daily life of the Irish missionaries, were soon transformed into the miracles of the saints. Bede believed these things, as all other men did, and records them with charming simplicity, just as he received them from bishop or abbot. Notwithstanding its errors, we owe to this work nearly all our knowledge of the eight centuries of our history following the landing of Caesar in Britain.",

    'The Normans were originally a hardy race of sea rovers inhabiting Scandinavia. In the tenth century they conquered a part of northern France, which is still called Normandy, and rapidly adopted French civilization and the French language. Their conquest of Anglo-Saxon England under William, Duke of Normandy, began with the battle of Hastings in 1066. The literature which they brought to England is remarkable for its bright, romantic tales of love and adventure, in marked contrast with the strength and somberness of Anglo-Saxon poetry. During the three centuries following Hastings, Normans and Saxons gradually united. The Anglo-Saxon speech simplified itself by dropping most of its Teutonic inflections, absorbed eventually a large part of the French vocabulary, and became our English language. English literature is also a combination of French and Saxon elements.',

    "Two great movements may be noted in the complex life of England during the fourteenth century. The first is political, and culminates in the reign of Edward III. It shows the growth of the English national spirit following the victories of Edward and the Black Prince on French soil, during the Hundred Years' War. In the rush of this great national movement, separating England from the political ties of France and, to a less degree, from ecclesiastical bondage to Rome, the mutual distrust and jealousy which had divided nobles and commons were momentarily swept aside by a wave of patriotic enthusiasm. The French language lost its official prestige, and English became the speech not only of the common people but of courts and Parliament as well.",

    'In 1370 Chaucer was sent abroad on the first of those diplomatic missions that were to occupy the greater part of the next fifteen years. Two years later he made his first official visit to Italy, to arrange a commercial treaty with Genoa, and from this time is noticeable a rapid development in his literary powers and the prominence of Italian literary influences. During the intervals between his different missions he filled various offices at home, chief of which was Comptroller of Customs at the port of London. An enormous amount of personal labor was involved; but Chaucer seems to have found time to follow his spirit into the new fields of Italian literature.',

    'Chaucer was a combined poet and man of affairs, with the latter predominating. Though dealing largely with ancient or medieval material, he has a curiously modern way of looking at life. Indeed, he is our only author preceding Shakespeare with whom we feel thoroughly at home. He threw aside the outgrown metrical romance, which was practically the only form of narrative in his day, invented the art of story-telling in verse, and brought it to a degree of perfection which has probably never since been equaled. Though a student of the classics, he lived wholly in the present, studied the men and women of his own time, painted them as they were, but added always a touch of kindly humor or romance to make them more interesting. So his mission appears to be simply to amuse himself and his readers.',

    'In all these theaters, probably, the stage consisted of a bare platform, with a curtain or "traverse" across the middle, separating the front from the rear stage. On the latter unexpected scenes or characters were "discovered" by simply drawing the curtain aside. At first little or no scenery was used, a gilded sign being the only announcement of a change of scene; and this very lack of scenery led to better acting, since the actors must be realistic enough to make the audience forget its shabby surroundings. By Shakespeare\'s day, however, painted scenery had appeared, first at university plays, and then in the regular theaters. In all our first plays female parts were taken by boy actors, who evidently were more distressing than the crude scenery, for contemporary literature has many satirical references to their acting.',

    'Probably the truth of the matter is to be found somewhere between these two extremes. Of his great genius there can be no question; but there are other things to consider. As we have already noticed, Shakespeare was trained, like his fellow workmen, first as an actor, second as a reviser of old plays, and last as an independent dramatist. He worked with other playwrights and learned their secret. Like them, he studied and followed the public taste, and his work indicates at least three stages, from his first somewhat crude experiments to his finished masterpieces. So it would seem that in Shakespeare we have the result of hard work and of orderly human development, quite as much as of transcendent genius.',

    'Shakespeare\'s poems, rather than his dramatic work, mark the beginning of his success. "Venus and Adonis" became immensely popular in London, and its dedication to the Earl of Southampton brought, according to tradition, a substantial money gift, which may have laid the foundation for Shakespeare\'s business success. He appears to have shrewdly invested his money, and soon became part owner of the Globe and Blackfriars theaters, in which his plays were presented by his own companies. His success and popularity grew amazingly. Within a decade of his unnoticed arrival in London he was one of the most famous actors and literary men in England.',

    'That Shakespeare thought little of his success and had no idea that his dramas were the greatest that the world ever produced seems evident from the fact that he made no attempt to collect or publish his works, or even to save his manuscripts, which were carelessly left to stage managers of the theaters, and so found their way ultimately to the ragman. After a few years of quiet life, of which we have less record than of hundreds of simple country gentlemen of the time, Shakespeare died on the probable anniversary of his birth, April 23, 1616. He was given a tomb in the chancel of the parish church, not because of his preeminence in literature, but because of his interest in the affairs of a country village.',

    'The work of these two men is so closely interwoven that, though Fletcher outlived Beaumont by nine years and the latter had no hand in some forty of the plays that bear their joint names, we still class them together, and only scholars attempt to separate their works so as to give each writer his due share. Unlike most of the Elizabethan dramatists, they both came from noble and cultured families and were university trained. Their work, in strong contrast with Jonson\'s, is intensely romantic, and in it all, however coarse or brutal the scene, there is still, as Emerson pointed out, the subtle "recognition of gentility."',

    "Laying aside the opinions of others, and relying only upon the facts of Bacon's life, we find on the one side the politician, cold, calculating, selfish, and on the other the literary and scientific man with an impressive devotion to truth for its own great sake; here a man using questionable means to advance his own interests, and there a man seeking with zeal and endless labor to penetrate the secret ways of Nature, with no other object than to advance the interests of his fellow-men. So, in our ignorance of the secret motives and springs of the man's life, judgment is necessarily suspended. Bacon was apparently one of those double natures that only God is competent to judge, because of the strange mixture of intellectual strength and moral weakness that is in them.",

    "The last part of Milton's life is a picture of solitary grandeur unequaled in literary history. With the Restoration all his labors and sacrifices for humanity were apparently wasted. From his retirement he could hear the bells and the shouts that welcomed back a vicious monarch, whose first act was to set his foot upon his people's neck. Milton was immediately marked for persecution, he remained for months in hiding, he was reduced to poverty, and his books were burned by the public hangman. His daughters, upon whom he depended in his blindness, rebelled at the task of reading to him and recording his thoughts.",

    "In the pleasant art of living with one's fellows, Addison is easily a master. It is due to his perfect expression of that art, of that new social life which, as we have noted, was characteristic of the Age of Anne, that Addison occupies such a large place in the history of literature. Of less power and originality than Swift, he nevertheless wields, and deserves to wield, a more lasting influence. Swift is the storm, roaring against the ice and frost of the late spring of English life. Addison is the sunshine, which melts the ice and dries the mud and makes the earth thrill with light and hope. Like Swift, he despised shams, but unlike him, he never lost faith in humanity; and in all his satires there is a gentle kindliness which makes one think better of his fellow-men, even while he laughs at their little vanities.",

    "Willowton is a village of some seventeen thousand population, large enough for the inhabitants to talk of \"going up the town\" when they mean the broad main street which stands on a gentle slope leading from the railway station to the church. This street, which is paved at the sides with nice old-world, ankle-twisting cobbles, boasts of two drapers', a chemist's, a saddler's, grocer's, and bootmaker's shops. Away in the less aristocratic parts of the village are the butchers and bakers, and the miscellaneous stores so dear to the country housewives. About the middle of the town, in the very widest part, is the bridge, and close to the bridge itself is the Wild Swan public-house, or rather hotel, as it calls itself.",

    'It was noon, and the sun was hot and the stream was low. There had been no rain for several weeks. The March winds had blown the seeds about; the wheat even drooped in the fields; April had refused her usual showers, and there was a dry, parched look everywhere while yet it was only May. Three men hung over the bridge, lazily resting their elbows on the parapet, and looking down into the water below at a large trout that was lying under a stone, waiting his opportunity to make his way further upstream to a deeper pool under the garden bank. Of these three "loafers," as the neighbours called them, one was a strong, well-built young man of one or two-and-twenty. His flushed face betrayed the fact that he had already visited the Wild Swan over the way; his great strong limbs were loosely knit; his big hands showed little signs of work; his lazy blue eyes looked as if they had never done anything more harmful or more useful than watch for trout.',

    'Many people with a wild desire to act prove failures on the stage, their inclinations are greater than their powers. Rarely is it the other way; nevertheless Fanny Kemble, in spite of her talent, hated the idea of going on the stage. At that time acting was considered barely respectable for a woman (1829). She was related to Sarah Siddons and John Kemble, a daughter of Charles and Fanny Kemble, and yet no dramatic fire burned in her veins. She was short and plain, with large feet and hands, her only charm her vivacity and expression. Ruin was imminent in the family when the girl was prevailed upon after much persuasion to play Juliet. Three weeks later she electrified London. Neither time nor success altered her repugnance for the stage, however.',

    'The pitcher did try it again; at least, he seemed to, but the ball dropped so low this time that it failed of being a strike by several inches. Chub looked pained. On the bench the coach was smiling dryly. The Blue pitcher awoke to the fact that he had been fooled. He sent a high ball straight over the plate and Chub let it go by. "Strike two!" called the umpire. The Blue stands cheered mightily. Two strikes and three balls! Chub gripped his bat hard. Again the pitcher shot the ball forward. It came straight and true for the plate, broke when a few feet away and came down at a weird tangent. Chub swung desperately and the ball glanced off the bat and went arching back into the stand. "Foul!" growled the umpire. Chub drew a deep breath of relief. Once more the pitcher poised himself and threw. The ball whirled by him and Chub dropped his bat and started across the plate, his heart in his mouth.',

    'Mr. Cole lived in a rather imposing white stone house within sight of the Park. The entrance was on the level with the sidewalk. Bay-trees in green tubs flanked the door which was guarded by a bronze grilling. The three boys were admitted by a uniformed butler and conducted into a tiny white-and-gold reception-room. As the heavy curtain fell again at the doorway after the retreating servant the visitors gazed at each other with awed surprise. Chub pretended to be fearful of trusting his weight to the slender chairs, and all three were grinning and giggling when the man appeared again, suddenly and noiselessly. Down a marble-tiled hall carpeted with narrow Oriental rugs in dull colors they were led to an elevator.',

    'Mr. Bowdon was exceedingly proud of him, and often took him to his club, that his friends might become acquainted with his young guest. Also Mr. Bowdon planned frequent excursions about the city, so that his nephew might enjoy the notable sights of London. These were indeed gala days for Samuel, and when the time came for him to go to school he could scarcely believe that ten weeks had flown since he had come up by the coach from his country home. It is doubtful whether Mr. Bowdon would have been willing to part with the lad even after so long a visit, but his business just at this time compelled him to take a long journey to the East Indies, and he desired to see the boy safely established before departing from London.',

    "One winter's day Samuel was walking slowly round Newgate market. He had no interest in Newgate market, but he must walk somewhere, and this was as good a place as any. A cold rain beat pitilessly upon his uncovered head, and from time to time he drew his blue coat more closely about him. Everyone but himself seemed in a hurry to get to places of shelter, and occasionally persons would pause to stare curiously at the lad who stood motionless in the downpour, gazing listlessly into shop windows. Whenever he found a deserted stair or vestibule, he stole in and read until he was curtly despatched by owner or policeman. Round and round the square he trod, jaded, famished, waiting for the hours to drag themselves by.",

    'The thing the Time Traveller held in his hand was a glittering metallic framework, scarcely larger than a small clock, and very delicately made. There was ivory in it, and some transparent crystalline substance. And now I must be explicit, for this that follows - unless his explanation is to be accepted - is an absolutely unaccountable thing. He took one of the small octagonal tables that were scattered about the room, and set it in front of the fire, with two legs on the hearthrug. On this table he placed the mechanism. Then he drew up a chair, and sat down. The only other object on the table was a small shaded lamp, the bright light of which fell upon the model. There were also perhaps a dozen candles about, two in brass candlesticks upon the mantel and several in sconces, so that the room was brilliantly illuminated.',

    'As soon as he got home, Utterson sat down and wrote to Jekyll, complaining of his exclusion from the house, and asking the cause of this unhappy break with Lanyon; and the next day brought him a long answer, often very pathetically worded, and sometimes darkly mysterious in drift. The quarrel with Lanyon was incurable. "I do not blame our old friend," Jekyll wrote, "but I share his view that we must never meet. I mean from henceforth to lead a life of extreme seclusion; you must not be surprised, nor must you doubt my friendship, if my door is often shut even to you. You must suffer me to go my own dark way. I have brought on myself a punishment and a danger that I cannot name. If I am the chief of sinners, I am the chief of sufferers also.',

    'Ralph Waldo Emerson was born in Boston, May 25, 1803. He was descended from a long line of New England ministers, men of refinement and education. As a school-boy he was quiet and retiring, reading a great deal, but not paying much attention to his lessons. He entered Harvard at the early age of fourteen, but never attained a high rank there, although he took a prize for an essay on Socrates, and was made class poet after several others had declined. Next to his reserve and the faultless propriety of his conduct, his contemporaries at college seemed most impressed by the great maturity of his mind. Emerson appears never to have been really a boy. He was always serene and thoughtful, impressing all who knew him with that spirituality which was his most distinguishing characteristic.',

    "Authors, no doubt, are always gratified when their works find favorable acceptance. The writer of this text has been doubly gratified, however, at the cordial reception and widespread use accorded to the present volume. This feeling does not arise from any narrow personal pride or selfish interest, but rather from the fact that the warm approval of the educational public has proved an important point; namely, that the fundamental truths of psychology, when put simply and concretely, can be made of interest and value to students of all ages from high school juniors up, and to the general public as well. More encouraging still, it has been demonstrated that the teachings of psychology can become immediately helpful, not only in study or teaching, but also in business or profession, in the control and guidance of the personal life, and in the problems met in the routine of the day's work or its play.",

    'Waves are most commonly caused by wind. Wind-driven waves, or surface waves, are created by the friction between wind and surface water. As wind blows across the surface of the ocean or a lake, the continual disturbance creates a wave crest. These types of waves are found globally across the open ocean and along the coast. More potentially hazardous waves can be caused by severe weather, like a hurricane. The strong winds and pressure from this type of severe storm causes storm surge, a series of long waves that are created far from shore in deeper water and intensify as they move closer to land.',

    'The first thing you need to do is get a skateboard. It\'s probably best to talk with a skateboarder to find a store that sells good quality skateboards, not just toys. Many skateboarders create their own "setup" but for your first board, someone at a skate shop should be able to help you. A helmet, elbow pads, knee pads, and wrist guards are important to get as well. It is better to wear all of those than to hurt yourself! Once you are ready to learn tricks, you might also need to buy some skate shoes. Then you\'ll need to find a place to skateboard. An empty parking lot or your driveway are good places to start.',

    "There are some basic movements you'll need to learn in order to skateboard. The first movement is to find your stance. Most skateboarders put their left foot towards the front of the board and use their right foot to push themselves. If you're left-handed, you might want to try standing in a \"goofy\" stance, with your right foot towards the front of the board and using your left foot to push. Make sure your foot isn't all the way at the front of the board, or it will tip forward. Next, you'll want to practice how to push off the ground and glide along on the board. Make sure most of your weight is over your front foot so that you can balance as your back foot pushes.",

    "Lisa has loved words for as long as she can remember. She loves the sounds words make, the shapes of words, and the way letters are arranged in words. Some of her favorite words are lollipop, balloon and purple. When Lisa has free time at school, she likes to write down words and doodle on the letters to create fun drawings. Sometimes she takes the drawings home to her parents, and sometimes her teacher pins them to the classroom bulletin board. One day, Lisa's art teacher walked into her classroom and noticed one of Lisa's recent pieces of word art. He was very impressed with her creativity and her word choice.",

    "In addition to the equipment they wear, there are other things that firefighters use to help them do their jobs more easily. They use fire trucks and fire engines that hold special tools. In the fire engines they have their tools organized so that they can quickly find and use them. Firefighters use hoses to connect to fire hydrants so that they can get a lot of water at one time. They use axes to break down doors for quick access to a fire. Also, they may bring smaller fire extinguishers in case the fire is a small one that they don't need a big hose for. They use ladders to reach people or animals in high places, such as second stories or trees.",

    "Lisa was nervous, but she stayed to see what her teacher wanted. When she found out Mrs. Roberts wanted her to enter the spelling bee, she was thrilled and honored. Usually only fifth graders enter the spelling bee. Lisa was even more excited when she heard that Mr. Jordan was going to help her study with the use of art. Lisa and Mr. Jordan met every day after school for the next three weeks. Mrs. Roberts had given them word lists to study. Lisa studied hard by turning each word into a drawing. When she wasn't sure what a word meant, her teacher would tell her and help her come up with an idea for the word art.",

    'The sky can be full of water. But most of the time you can\'t see it. The drops of water are too small to see. They have turned into a gas called water vapor. As the water vapor goes higher in the sky, the air gets cooler. The cooler air causes the water droplets to start to stick to things like bits of dust, ice or sea salt. Most of the water in clouds is in very small droplets. The droplets are so light they float in the air. Sometimes those droplets join together and turn into larger drops. When that happens, gravity causes them to fall to Earth. We call the falling water drops "rain." When the air is colder, the water may form snowflakes instead.',

    'There was a boy who really wanted to open his own business. He loved watching shows on TV about people who invented great things and helped other people love their inventions, too. He tried to learn about how people started their own businesses and how they got their great ideas, but a lot of it was too hard for him to understand yet. His mom suggested that he look around the community for a business leader who might be able to help him understand, so that he could start his own business one day. One day, he and his mom were out getting ice cream, and the shop owner, Mr. Warner, was the one serving them.',

    "Will couldn't wait for September when school would start. It was early August, and he was at the same summer camp he had been going to for the last five years. His dad went to the camp when he was a boy and loved it, so Will didn't want to disappoint his dad by telling him that he didn't even like it. He wrote to his mom and asked her if she would pick him up early, but he didn't want his mom to tell his dad. Will was looking forward to the meals that his mom would make when he got home. Every time he ate a camp meal he imagined he was eating his mom's cooking. All of a sudden, the food didn't taste as bad.",

    'Firefighters have to take physical tests to make sure their bodies are strong enough to do all of the work required. One of the most important parts of being a firefighter is working as a team. Firefighters have to work together to stop fires, even down to holding the hose together! Some firefighters stay at the fire station for an entire day, including overnight. When there is not a fire going on, firefighters make sure all of their equipment is clean and in working order. After dinner, they are able to use their free time to relax. Firefighting is stressful, though. Firefighters never know when a fire or other emergency is going to happen, so they have to be ready at all times.',

    "There was a young boy wandering through the trees. The air smelled of oranges all around him. The weather was perfect, the sun was shining, and the oranges were growing bigger by the day. He liked to walk through the groves, and loved the smell of the oranges, but he didn't like that he and his family ate oranges all the time. Sometimes, he wanted to avoid them for weeks at a time. He wished his family could grow other things, like corn, or the ingredients for his favorite dip that his mom made. His mouth watered just thinking about his favorite dip. Yes, those ingredients would be better than oranges all the time.",

    'Astronauts put on their spacesuits several hours before a spacewalk. The suits are pressurized. This means that the suits are filled with oxygen. Once in their suits, astronauts breathe pure oxygen for a few hours. Breathing only oxygen gets rid of all the nitrogen in an astronaut\'s body. If they didn\'t get rid of the nitrogen, the astronauts might get gas bubbles in their body when they walked in space. These gas bubbles can cause astronauts to feel pain in their shoulders, elbows, wrists and knees. This pain is called getting "the bends" because it affects the places where the body bends. Scuba divers can also get "the bends."',

    'One way astronauts train for spacewalks is by going for a swim. Floating in space is a lot like floating in water. Astronauts practice spacewalks underwater in a large swimming pool. Astronauts train seven hours in the pool for every one hour they will spend on a spacewalk. Another way astronauts practice for a spacewalk is by using virtual reality. This is sort of like playing a video game. Astronauts wear a helmet with a video screen inside. They also wear special gloves. A video of what they will see during a spacewalk is shown on the screen inside the helmet. When the astronaut moves, the special gloves allow the movements to be shown with the video. The virtual reality simulation looks and feels just like a spacewalk.',

    "Dancers must go through a lot of training. Many take classes almost daily if they'd like to be professional ballet dancers. The movements are demanding on their bodies, so they need to practice often to keep up their strength. That also means that dancers need to take very good care of their bodies, though, so their bodies can keep up with the dancing! Dancers need to be well rested and eat healthy meals. They also should drink plenty of water and listen to their bodies by resting if that's what their bodies need. They should start slowly when learning new steps, so their bodies have time to get used to the steps and not get injured.",


];